"""empty message

Revision ID: 5d2c80999619
Revises: e93e9ca3cd43
Create Date: 2024-03-15 16:53:29.141007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2c80999619'
down_revision = 'e93e9ca3cd43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_list', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
